export type ProgressionAchievementCategory = "IDENTITY" | "COMMUNITY" | "SOCIAL" | "PROGRESS";

export type ProgressionMetric =
  | "PROFILE_COMPLETE"
  | "EMAIL_VERIFIED"
  | "OAUTH_CONNECTIONS"
  | "GLOBAL_MESSAGES"
  | "DIRECT_MESSAGES"
  | "FRIENDSHIPS"
  | "LEVEL"
  | "XP";

export interface ProgressionRequirement {
  metric: ProgressionMetric;
  min: number;
}

export interface ProgressionAchievement {
  code: string;
  category: ProgressionAchievementCategory;
  iconKey: string;
  xpReward: number;
  coinReward: number;
  requirements: readonly ProgressionRequirement[];
  copy: {
    es: { title: string; description: string };
    en: { title: string; description: string };
  };
}

/** Original v0.6 milestones. Kept intact for existing users and reward history. */
export const LEGACY_PROGRESSION_ACHIEVEMENTS = [
  {
    code: "PROFILE_COMPLETE",
    category: "IDENTITY",
    iconKey: "star",
    xpReward: 15,
    coinReward: 10,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }],
    copy: { es: { title: "Perfil listo", description: "Agregá una bio y un detalle personal de tu perfil." }, en: { title: "Profile ready", description: "Add a bio and a personal profile detail." } },
  },
  {
    code: "EMAIL_VERIFIED",
    category: "IDENTITY",
    iconKey: "medal",
    xpReward: 15,
    coinReward: 10,
    requirements: [{ metric: "EMAIL_VERIFIED", min: 1 }],
    copy: { es: { title: "Verificado", description: "Verificá tu dirección de email." }, en: { title: "Verified", description: "Verify your email address." } },
  },
  {
    code: "OAUTH_CONNECTED",
    category: "IDENTITY",
    iconKey: "zap",
    xpReward: 15,
    coinReward: 10,
    requirements: [{ metric: "OAUTH_CONNECTIONS", min: 1 }],
    copy: { es: { title: "Conectado", description: "Vinculá una cuenta de Google o Discord." }, en: { title: "Connected", description: "Link a Google or Discord account." } },
  },
  {
    code: "FIRST_GLOBAL_MESSAGE",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 10,
    coinReward: 5,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 1 }],
    copy: { es: { title: "Primer saludo", description: "Enviá tu primer mensaje en el chat global." }, en: { title: "First hello", description: "Send your first message in global chat." } },
  },
  {
    code: "GLOBAL_REGULAR",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 15,
    coinReward: 10,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 10 }],
    copy: { es: { title: "Habitual de la comunidad", description: "Enviá 10 mensajes en el chat global." }, en: { title: "Community regular", description: "Send 10 messages in global chat." } },
  },
  {
    code: "FIRST_DM",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 10,
    coinReward: 5,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 1 }],
    copy: { es: { title: "Conexión directa", description: "Enviá tu primer mensaje privado." }, en: { title: "Direct connection", description: "Send your first direct message." } },
  },
  {
    code: "DM_REGULAR",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 15,
    coinReward: 10,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 10 }],
    copy: { es: { title: "En contacto", description: "Enviá 10 mensajes privados." }, en: { title: "Keeping in touch", description: "Send 10 direct messages." } },
  },
  {
    code: "FIRST_FRIEND",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 15,
    coinReward: 10,
    requirements: [{ metric: "FRIENDSHIPS", min: 1 }],
    copy: { es: { title: "Primer amigo", description: "Hacete amigo de otro miembro." }, en: { title: "First friend", description: "Become friends with another member." } },
  },
  {
    code: "SOCIAL_FIVE",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 25,
    coinReward: 20,
    requirements: [{ metric: "FRIENDSHIPS", min: 5 }],
    copy: { es: { title: "Círculo social", description: "Creá cinco conexiones en la comunidad." }, en: { title: "Social circle", description: "Make five community connections." } },
  },
  {
    code: "LEVEL_FIVE",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 20,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 5 }],
    copy: { es: { title: "Estrella en ascenso", description: "Alcanzá el nivel 5." }, en: { title: "Rising star", description: "Reach level 5." } },
  },
  {
    code: "LEVEL_TEN",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 30,
    coinReward: 30,
    requirements: [{ metric: "LEVEL", min: 10 }],
    copy: { es: { title: "Leyenda de la comunidad", description: "Alcanzá el nivel 10." }, en: { title: "Community legend", description: "Reach level 10." } },
  }
] as const satisfies readonly ProgressionAchievement[];

/**
 * Production catalogue added after v0.12. These 200 milestones are code-owned,
 * immutable by normal admin CRUD, and use server-derived facts only. They do
 * not grant XP, avoiding achievement-to-level recursion; TFL Coin rewards are
 * idempotent through the wallet ledger.
 */
export const PRODUCTION_PROGRESSION_ACHIEVEMENTS = [
  {
    code: "GLOBAL_01_1",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 25 }],
    copy: { es: { title: "Primeros ecos I", description: "Enviá 25 mensajes en el chat global." }, en: { title: "First echoes I", description: "Send 25 messages in global chat." } },
  },
  {
    code: "GLOBAL_01_2",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 50 }],
    copy: { es: { title: "Primeros ecos II", description: "Enviá 50 mensajes en el chat global." }, en: { title: "First echoes II", description: "Send 50 messages in global chat." } },
  },
  {
    code: "GLOBAL_01_3",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 75 }],
    copy: { es: { title: "Primeros ecos III", description: "Enviá 75 mensajes en el chat global." }, en: { title: "First echoes III", description: "Send 75 messages in global chat." } },
  },
  {
    code: "GLOBAL_01_4",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 100 }],
    copy: { es: { title: "Primeros ecos IV", description: "Enviá 100 mensajes en el chat global." }, en: { title: "First echoes IV", description: "Send 100 messages in global chat." } },
  },
  {
    code: "GLOBAL_01_5",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 150 }],
    copy: { es: { title: "Primeros ecos V", description: "Enviá 150 mensajes en el chat global." }, en: { title: "First echoes V", description: "Send 150 messages in global chat." } },
  },
  {
    code: "GLOBAL_02_1",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 200 }],
    copy: { es: { title: "Conversación en marcha I", description: "Enviá 200 mensajes en el chat global." }, en: { title: "Conversation in motion I", description: "Send 200 messages in global chat." } },
  },
  {
    code: "GLOBAL_02_2",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 300 }],
    copy: { es: { title: "Conversación en marcha II", description: "Enviá 300 mensajes en el chat global." }, en: { title: "Conversation in motion II", description: "Send 300 messages in global chat." } },
  },
  {
    code: "GLOBAL_02_3",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 400 }],
    copy: { es: { title: "Conversación en marcha III", description: "Enviá 400 mensajes en el chat global." }, en: { title: "Conversation in motion III", description: "Send 400 messages in global chat." } },
  },
  {
    code: "GLOBAL_02_4",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 500 }],
    copy: { es: { title: "Conversación en marcha IV", description: "Enviá 500 mensajes en el chat global." }, en: { title: "Conversation in motion IV", description: "Send 500 messages in global chat." } },
  },
  {
    code: "GLOBAL_02_5",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 750 }],
    copy: { es: { title: "Conversación en marcha V", description: "Enviá 750 mensajes en el chat global." }, en: { title: "Conversation in motion V", description: "Send 750 messages in global chat." } },
  },
  {
    code: "GLOBAL_03_1",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 1000 }],
    copy: { es: { title: "Voz frecuente I", description: "Enviá 1.000 mensajes en el chat global." }, en: { title: "Frequent voice I", description: "Send 1,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_03_2",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 1250 }],
    copy: { es: { title: "Voz frecuente II", description: "Enviá 1.250 mensajes en el chat global." }, en: { title: "Frequent voice II", description: "Send 1,250 messages in global chat." } },
  },
  {
    code: "GLOBAL_03_3",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 1500 }],
    copy: { es: { title: "Voz frecuente III", description: "Enviá 1.500 mensajes en el chat global." }, en: { title: "Frequent voice III", description: "Send 1,500 messages in global chat." } },
  },
  {
    code: "GLOBAL_03_4",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 2000 }],
    copy: { es: { title: "Voz frecuente IV", description: "Enviá 2.000 mensajes en el chat global." }, en: { title: "Frequent voice IV", description: "Send 2,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_03_5",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 2500 }],
    copy: { es: { title: "Voz frecuente V", description: "Enviá 2.500 mensajes en el chat global." }, en: { title: "Frequent voice V", description: "Send 2,500 messages in global chat." } },
  },
  {
    code: "GLOBAL_04_1",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 3000 }],
    copy: { es: { title: "Voz de la comunidad I", description: "Enviá 3.000 mensajes en el chat global." }, en: { title: "Community voice I", description: "Send 3,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_04_2",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 4000 }],
    copy: { es: { title: "Voz de la comunidad II", description: "Enviá 4.000 mensajes en el chat global." }, en: { title: "Community voice II", description: "Send 4,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_04_3",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 5000 }],
    copy: { es: { title: "Voz de la comunidad III", description: "Enviá 5.000 mensajes en el chat global." }, en: { title: "Community voice III", description: "Send 5,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_04_4",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 7500 }],
    copy: { es: { title: "Voz de la comunidad IV", description: "Enviá 7.500 mensajes en el chat global." }, en: { title: "Community voice IV", description: "Send 7,500 messages in global chat." } },
  },
  {
    code: "GLOBAL_04_5",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 10000 }],
    copy: { es: { title: "Voz de la comunidad V", description: "Enviá 10.000 mensajes en el chat global." }, en: { title: "Community voice V", description: "Send 10,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_05_1",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 12500 }],
    copy: { es: { title: "Cronista I", description: "Enviá 12.500 mensajes en el chat global." }, en: { title: "Chronicler I", description: "Send 12,500 messages in global chat." } },
  },
  {
    code: "GLOBAL_05_2",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 15000 }],
    copy: { es: { title: "Cronista II", description: "Enviá 15.000 mensajes en el chat global." }, en: { title: "Chronicler II", description: "Send 15,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_05_3",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 20000 }],
    copy: { es: { title: "Cronista III", description: "Enviá 20.000 mensajes en el chat global." }, en: { title: "Chronicler III", description: "Send 20,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_05_4",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 25000 }],
    copy: { es: { title: "Cronista IV", description: "Enviá 25.000 mensajes en el chat global." }, en: { title: "Chronicler IV", description: "Send 25,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_05_5",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 30000 }],
    copy: { es: { title: "Cronista V", description: "Enviá 30.000 mensajes en el chat global." }, en: { title: "Chronicler V", description: "Send 30,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_06_1",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 40000 }],
    copy: { es: { title: "Pulso del chat I", description: "Enviá 40.000 mensajes en el chat global." }, en: { title: "Chat pulse I", description: "Send 40,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_06_2",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 50000 }],
    copy: { es: { title: "Pulso del chat II", description: "Enviá 50.000 mensajes en el chat global." }, en: { title: "Chat pulse II", description: "Send 50,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_06_3",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 60000 }],
    copy: { es: { title: "Pulso del chat III", description: "Enviá 60.000 mensajes en el chat global." }, en: { title: "Chat pulse III", description: "Send 60,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_06_4",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 75000 }],
    copy: { es: { title: "Pulso del chat IV", description: "Enviá 75.000 mensajes en el chat global." }, en: { title: "Chat pulse IV", description: "Send 75,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_06_5",
    category: "COMMUNITY",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 90000 }],
    copy: { es: { title: "Pulso del chat V", description: "Enviá 90.000 mensajes en el chat global." }, en: { title: "Chat pulse V", description: "Send 90,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_07_1",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 100000 }],
    copy: { es: { title: "Resonancia I", description: "Enviá 100.000 mensajes en el chat global." }, en: { title: "Resonance I", description: "Send 100,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_07_2",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 125000 }],
    copy: { es: { title: "Resonancia II", description: "Enviá 125.000 mensajes en el chat global." }, en: { title: "Resonance II", description: "Send 125,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_07_3",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 150000 }],
    copy: { es: { title: "Resonancia III", description: "Enviá 150.000 mensajes en el chat global." }, en: { title: "Resonance III", description: "Send 150,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_07_4",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 175000 }],
    copy: { es: { title: "Resonancia IV", description: "Enviá 175.000 mensajes en el chat global." }, en: { title: "Resonance IV", description: "Send 175,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_07_5",
    category: "COMMUNITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 200000 }],
    copy: { es: { title: "Resonancia V", description: "Enviá 200.000 mensajes en el chat global." }, en: { title: "Resonance V", description: "Send 200,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_08_1",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 250000 }],
    copy: { es: { title: "Presencia constante I", description: "Enviá 250.000 mensajes en el chat global." }, en: { title: "Steady presence I", description: "Send 250,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_08_2",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 300000 }],
    copy: { es: { title: "Presencia constante II", description: "Enviá 300.000 mensajes en el chat global." }, en: { title: "Steady presence II", description: "Send 300,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_08_3",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 350000 }],
    copy: { es: { title: "Presencia constante III", description: "Enviá 350.000 mensajes en el chat global." }, en: { title: "Steady presence III", description: "Send 350,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_08_4",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 400000 }],
    copy: { es: { title: "Presencia constante IV", description: "Enviá 400.000 mensajes en el chat global." }, en: { title: "Steady presence IV", description: "Send 400,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_08_5",
    category: "COMMUNITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 450000 }],
    copy: { es: { title: "Presencia constante V", description: "Enviá 450.000 mensajes en el chat global." }, en: { title: "Steady presence V", description: "Send 450,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_09_1",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 500000 }],
    copy: { es: { title: "Archivo viviente I", description: "Enviá 500.000 mensajes en el chat global." }, en: { title: "Living archive I", description: "Send 500,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_09_2",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 600000 }],
    copy: { es: { title: "Archivo viviente II", description: "Enviá 600.000 mensajes en el chat global." }, en: { title: "Living archive II", description: "Send 600,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_09_3",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 700000 }],
    copy: { es: { title: "Archivo viviente III", description: "Enviá 700.000 mensajes en el chat global." }, en: { title: "Living archive III", description: "Send 700,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_09_4",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 800000 }],
    copy: { es: { title: "Archivo viviente IV", description: "Enviá 800.000 mensajes en el chat global." }, en: { title: "Living archive IV", description: "Send 800,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_09_5",
    category: "COMMUNITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 900000 }],
    copy: { es: { title: "Archivo viviente V", description: "Enviá 900.000 mensajes en el chat global." }, en: { title: "Living archive V", description: "Send 900,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_10_1",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 925000 }],
    copy: { es: { title: "Voz legendaria I", description: "Enviá 925.000 mensajes en el chat global." }, en: { title: "Legendary voice I", description: "Send 925,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_10_2",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 950000 }],
    copy: { es: { title: "Voz legendaria II", description: "Enviá 950.000 mensajes en el chat global." }, en: { title: "Legendary voice II", description: "Send 950,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_10_3",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 975000 }],
    copy: { es: { title: "Voz legendaria III", description: "Enviá 975.000 mensajes en el chat global." }, en: { title: "Legendary voice III", description: "Send 975,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_10_4",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 990000 }],
    copy: { es: { title: "Voz legendaria IV", description: "Enviá 990.000 mensajes en el chat global." }, en: { title: "Legendary voice IV", description: "Send 990,000 messages in global chat." } },
  },
  {
    code: "GLOBAL_10_5",
    category: "COMMUNITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 1000000 }],
    copy: { es: { title: "Voz legendaria V", description: "Enviá 1.000.000 mensajes en el chat global." }, en: { title: "Legendary voice V", description: "Send 1,000,000 messages in global chat." } },
  },
  {
    code: "DM_01_1",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 25 }],
    copy: { es: { title: "En confianza I", description: "Enviá 25 mensajes privados." }, en: { title: "In confidence I", description: "Send 25 direct messages." } },
  },
  {
    code: "DM_01_2",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 50 }],
    copy: { es: { title: "En confianza II", description: "Enviá 50 mensajes privados." }, en: { title: "In confidence II", description: "Send 50 direct messages." } },
  },
  {
    code: "DM_01_3",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 75 }],
    copy: { es: { title: "En confianza III", description: "Enviá 75 mensajes privados." }, en: { title: "In confidence III", description: "Send 75 direct messages." } },
  },
  {
    code: "DM_01_4",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 100 }],
    copy: { es: { title: "En confianza IV", description: "Enviá 100 mensajes privados." }, en: { title: "In confidence IV", description: "Send 100 direct messages." } },
  },
  {
    code: "DM_01_5",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 150 }],
    copy: { es: { title: "En confianza V", description: "Enviá 150 mensajes privados." }, en: { title: "In confidence V", description: "Send 150 direct messages." } },
  },
  {
    code: "DM_02_1",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 200 }],
    copy: { es: { title: "Conversación continua I", description: "Enviá 200 mensajes privados." }, en: { title: "Continuous conversation I", description: "Send 200 direct messages." } },
  },
  {
    code: "DM_02_2",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 300 }],
    copy: { es: { title: "Conversación continua II", description: "Enviá 300 mensajes privados." }, en: { title: "Continuous conversation II", description: "Send 300 direct messages." } },
  },
  {
    code: "DM_02_3",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 400 }],
    copy: { es: { title: "Conversación continua III", description: "Enviá 400 mensajes privados." }, en: { title: "Continuous conversation III", description: "Send 400 direct messages." } },
  },
  {
    code: "DM_02_4",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 500 }],
    copy: { es: { title: "Conversación continua IV", description: "Enviá 500 mensajes privados." }, en: { title: "Continuous conversation IV", description: "Send 500 direct messages." } },
  },
  {
    code: "DM_02_5",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 750 }],
    copy: { es: { title: "Conversación continua V", description: "Enviá 750 mensajes privados." }, en: { title: "Continuous conversation V", description: "Send 750 direct messages." } },
  },
  {
    code: "DM_03_1",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 1000 }],
    copy: { es: { title: "Línea abierta I", description: "Enviá 1.000 mensajes privados." }, en: { title: "Open line I", description: "Send 1,000 direct messages." } },
  },
  {
    code: "DM_03_2",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 1500 }],
    copy: { es: { title: "Línea abierta II", description: "Enviá 1.500 mensajes privados." }, en: { title: "Open line II", description: "Send 1,500 direct messages." } },
  },
  {
    code: "DM_03_3",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 2000 }],
    copy: { es: { title: "Línea abierta III", description: "Enviá 2.000 mensajes privados." }, en: { title: "Open line III", description: "Send 2,000 direct messages." } },
  },
  {
    code: "DM_03_4",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 3000 }],
    copy: { es: { title: "Línea abierta IV", description: "Enviá 3.000 mensajes privados." }, en: { title: "Open line IV", description: "Send 3,000 direct messages." } },
  },
  {
    code: "DM_03_5",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 4000 }],
    copy: { es: { title: "Línea abierta V", description: "Enviá 4.000 mensajes privados." }, en: { title: "Open line V", description: "Send 4,000 direct messages." } },
  },
  {
    code: "DM_04_1",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 5000 }],
    copy: { es: { title: "Siempre en contacto I", description: "Enviá 5.000 mensajes privados." }, en: { title: "Always in touch I", description: "Send 5,000 direct messages." } },
  },
  {
    code: "DM_04_2",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 7500 }],
    copy: { es: { title: "Siempre en contacto II", description: "Enviá 7.500 mensajes privados." }, en: { title: "Always in touch II", description: "Send 7,500 direct messages." } },
  },
  {
    code: "DM_04_3",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 10000 }],
    copy: { es: { title: "Siempre en contacto III", description: "Enviá 10.000 mensajes privados." }, en: { title: "Always in touch III", description: "Send 10,000 direct messages." } },
  },
  {
    code: "DM_04_4",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 12500 }],
    copy: { es: { title: "Siempre en contacto IV", description: "Enviá 12.500 mensajes privados." }, en: { title: "Always in touch IV", description: "Send 12,500 direct messages." } },
  },
  {
    code: "DM_04_5",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 15000 }],
    copy: { es: { title: "Siempre en contacto V", description: "Enviá 15.000 mensajes privados." }, en: { title: "Always in touch V", description: "Send 15,000 direct messages." } },
  },
  {
    code: "DM_05_1",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 20000 }],
    copy: { es: { title: "Confidente I", description: "Enviá 20.000 mensajes privados." }, en: { title: "Confidant I", description: "Send 20,000 direct messages." } },
  },
  {
    code: "DM_05_2",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 25000 }],
    copy: { es: { title: "Confidente II", description: "Enviá 25.000 mensajes privados." }, en: { title: "Confidant II", description: "Send 25,000 direct messages." } },
  },
  {
    code: "DM_05_3",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 30000 }],
    copy: { es: { title: "Confidente III", description: "Enviá 30.000 mensajes privados." }, en: { title: "Confidant III", description: "Send 30,000 direct messages." } },
  },
  {
    code: "DM_05_4",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 40000 }],
    copy: { es: { title: "Confidente IV", description: "Enviá 40.000 mensajes privados." }, en: { title: "Confidant IV", description: "Send 40,000 direct messages." } },
  },
  {
    code: "DM_05_5",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 50000 }],
    copy: { es: { title: "Confidente V", description: "Enviá 50.000 mensajes privados." }, en: { title: "Confidant V", description: "Send 50,000 direct messages." } },
  },
  {
    code: "DM_06_1",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 60000 }],
    copy: { es: { title: "Puentes privados I", description: "Enviá 60.000 mensajes privados." }, en: { title: "Private bridges I", description: "Send 60,000 direct messages." } },
  },
  {
    code: "DM_06_2",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 75000 }],
    copy: { es: { title: "Puentes privados II", description: "Enviá 75.000 mensajes privados." }, en: { title: "Private bridges II", description: "Send 75,000 direct messages." } },
  },
  {
    code: "DM_06_3",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 90000 }],
    copy: { es: { title: "Puentes privados III", description: "Enviá 90.000 mensajes privados." }, en: { title: "Private bridges III", description: "Send 90,000 direct messages." } },
  },
  {
    code: "DM_06_4",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 100000 }],
    copy: { es: { title: "Puentes privados IV", description: "Enviá 100.000 mensajes privados." }, en: { title: "Private bridges IV", description: "Send 100,000 direct messages." } },
  },
  {
    code: "DM_06_5",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 125000 }],
    copy: { es: { title: "Puentes privados V", description: "Enviá 125.000 mensajes privados." }, en: { title: "Private bridges V", description: "Send 125,000 direct messages." } },
  },
  {
    code: "DM_07_1",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 150000 }],
    copy: { es: { title: "Mensajero veterano I", description: "Enviá 150.000 mensajes privados." }, en: { title: "Veteran messenger I", description: "Send 150,000 direct messages." } },
  },
  {
    code: "DM_07_2",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 175000 }],
    copy: { es: { title: "Mensajero veterano II", description: "Enviá 175.000 mensajes privados." }, en: { title: "Veteran messenger II", description: "Send 175,000 direct messages." } },
  },
  {
    code: "DM_07_3",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 200000 }],
    copy: { es: { title: "Mensajero veterano III", description: "Enviá 200.000 mensajes privados." }, en: { title: "Veteran messenger III", description: "Send 200,000 direct messages." } },
  },
  {
    code: "DM_07_4",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 250000 }],
    copy: { es: { title: "Mensajero veterano IV", description: "Enviá 250.000 mensajes privados." }, en: { title: "Veteran messenger IV", description: "Send 250,000 direct messages." } },
  },
  {
    code: "DM_07_5",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 300000 }],
    copy: { es: { title: "Mensajero veterano V", description: "Enviá 300.000 mensajes privados." }, en: { title: "Veteran messenger V", description: "Send 300,000 direct messages." } },
  },
  {
    code: "DM_08_1",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 350000 }],
    copy: { es: { title: "Conexión interminable I", description: "Enviá 350.000 mensajes privados." }, en: { title: "Endless connection I", description: "Send 350,000 direct messages." } },
  },
  {
    code: "DM_08_2",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 400000 }],
    copy: { es: { title: "Conexión interminable II", description: "Enviá 400.000 mensajes privados." }, en: { title: "Endless connection II", description: "Send 400,000 direct messages." } },
  },
  {
    code: "DM_08_3",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 450000 }],
    copy: { es: { title: "Conexión interminable III", description: "Enviá 450.000 mensajes privados." }, en: { title: "Endless connection III", description: "Send 450,000 direct messages." } },
  },
  {
    code: "DM_08_4",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 475000 }],
    copy: { es: { title: "Conexión interminable IV", description: "Enviá 475.000 mensajes privados." }, en: { title: "Endless connection IV", description: "Send 475,000 direct messages." } },
  },
  {
    code: "DM_08_5",
    category: "SOCIAL",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "DIRECT_MESSAGES", min: 500000 }],
    copy: { es: { title: "Conexión interminable V", description: "Enviá 500.000 mensajes privados." }, en: { title: "Endless connection V", description: "Send 500,000 direct messages." } },
  },
  {
    code: "FRIENDS_01_1",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "FRIENDSHIPS", min: 2 }],
    copy: { es: { title: "Nuevas conexiones I", description: "Alcanzá 2 amistades aceptadas." }, en: { title: "New connections I", description: "Reach 2 accepted friendships." } },
  },
  {
    code: "FRIENDS_01_2",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "FRIENDSHIPS", min: 3 }],
    copy: { es: { title: "Nuevas conexiones II", description: "Alcanzá 3 amistades aceptadas." }, en: { title: "New connections II", description: "Reach 3 accepted friendships." } },
  },
  {
    code: "FRIENDS_01_3",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "FRIENDSHIPS", min: 4 }],
    copy: { es: { title: "Nuevas conexiones III", description: "Alcanzá 4 amistades aceptadas." }, en: { title: "New connections III", description: "Reach 4 accepted friendships." } },
  },
  {
    code: "FRIENDS_01_4",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "FRIENDSHIPS", min: 6 }],
    copy: { es: { title: "Nuevas conexiones IV", description: "Alcanzá 6 amistades aceptadas." }, en: { title: "New connections IV", description: "Reach 6 accepted friendships." } },
  },
  {
    code: "FRIENDS_01_5",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "FRIENDSHIPS", min: 8 }],
    copy: { es: { title: "Nuevas conexiones V", description: "Alcanzá 8 amistades aceptadas." }, en: { title: "New connections V", description: "Reach 8 accepted friendships." } },
  },
  {
    code: "FRIENDS_02_1",
    category: "SOCIAL",
    iconKey: "star",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "FRIENDSHIPS", min: 10 }],
    copy: { es: { title: "Círculo creciente I", description: "Alcanzá 10 amistades aceptadas." }, en: { title: "Growing circle I", description: "Reach 10 accepted friendships." } },
  },
  {
    code: "FRIENDS_02_2",
    category: "SOCIAL",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "FRIENDSHIPS", min: 12 }],
    copy: { es: { title: "Círculo creciente II", description: "Alcanzá 12 amistades aceptadas." }, en: { title: "Growing circle II", description: "Reach 12 accepted friendships." } },
  },
  {
    code: "FRIENDS_02_3",
    category: "SOCIAL",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "FRIENDSHIPS", min: 15 }],
    copy: { es: { title: "Círculo creciente III", description: "Alcanzá 15 amistades aceptadas." }, en: { title: "Growing circle III", description: "Reach 15 accepted friendships." } },
  },
  {
    code: "FRIENDS_02_4",
    category: "SOCIAL",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "FRIENDSHIPS", min: 20 }],
    copy: { es: { title: "Círculo creciente IV", description: "Alcanzá 20 amistades aceptadas." }, en: { title: "Growing circle IV", description: "Reach 20 accepted friendships." } },
  },
  {
    code: "FRIENDS_02_5",
    category: "SOCIAL",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "FRIENDSHIPS", min: 25 }],
    copy: { es: { title: "Círculo creciente V", description: "Alcanzá 25 amistades aceptadas." }, en: { title: "Growing circle V", description: "Reach 25 accepted friendships." } },
  },
  {
    code: "FRIENDS_03_1",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "FRIENDSHIPS", min: 30 }],
    copy: { es: { title: "Red cercana I", description: "Alcanzá 30 amistades aceptadas." }, en: { title: "Close network I", description: "Reach 30 accepted friendships." } },
  },
  {
    code: "FRIENDS_03_2",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "FRIENDSHIPS", min: 35 }],
    copy: { es: { title: "Red cercana II", description: "Alcanzá 35 amistades aceptadas." }, en: { title: "Close network II", description: "Reach 35 accepted friendships." } },
  },
  {
    code: "FRIENDS_03_3",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "FRIENDSHIPS", min: 40 }],
    copy: { es: { title: "Red cercana III", description: "Alcanzá 40 amistades aceptadas." }, en: { title: "Close network III", description: "Reach 40 accepted friendships." } },
  },
  {
    code: "FRIENDS_03_4",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "FRIENDSHIPS", min: 50 }],
    copy: { es: { title: "Red cercana IV", description: "Alcanzá 50 amistades aceptadas." }, en: { title: "Close network IV", description: "Reach 50 accepted friendships." } },
  },
  {
    code: "FRIENDS_03_5",
    category: "SOCIAL",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "FRIENDSHIPS", min: 60 }],
    copy: { es: { title: "Red cercana V", description: "Alcanzá 60 amistades aceptadas." }, en: { title: "Close network V", description: "Reach 60 accepted friendships." } },
  },
  {
    code: "FRIENDS_04_1",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "FRIENDSHIPS", min: 75 }],
    copy: { es: { title: "Persona conocida I", description: "Alcanzá 75 amistades aceptadas." }, en: { title: "Known face I", description: "Reach 75 accepted friendships." } },
  },
  {
    code: "FRIENDS_04_2",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "FRIENDSHIPS", min: 90 }],
    copy: { es: { title: "Persona conocida II", description: "Alcanzá 90 amistades aceptadas." }, en: { title: "Known face II", description: "Reach 90 accepted friendships." } },
  },
  {
    code: "FRIENDS_04_3",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "FRIENDSHIPS", min: 100 }],
    copy: { es: { title: "Persona conocida III", description: "Alcanzá 100 amistades aceptadas." }, en: { title: "Known face III", description: "Reach 100 accepted friendships." } },
  },
  {
    code: "FRIENDS_04_4",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "FRIENDSHIPS", min: 125 }],
    copy: { es: { title: "Persona conocida IV", description: "Alcanzá 125 amistades aceptadas." }, en: { title: "Known face IV", description: "Reach 125 accepted friendships." } },
  },
  {
    code: "FRIENDS_04_5",
    category: "SOCIAL",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "FRIENDSHIPS", min: 150 }],
    copy: { es: { title: "Persona conocida V", description: "Alcanzá 150 amistades aceptadas." }, en: { title: "Known face V", description: "Reach 150 accepted friendships." } },
  },
  {
    code: "FRIENDS_05_1",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "FRIENDSHIPS", min: 175 }],
    copy: { es: { title: "Conector social I", description: "Alcanzá 175 amistades aceptadas." }, en: { title: "Social connector I", description: "Reach 175 accepted friendships." } },
  },
  {
    code: "FRIENDS_05_2",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "FRIENDSHIPS", min: 200 }],
    copy: { es: { title: "Conector social II", description: "Alcanzá 200 amistades aceptadas." }, en: { title: "Social connector II", description: "Reach 200 accepted friendships." } },
  },
  {
    code: "FRIENDS_05_3",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "FRIENDSHIPS", min: 250 }],
    copy: { es: { title: "Conector social III", description: "Alcanzá 250 amistades aceptadas." }, en: { title: "Social connector III", description: "Reach 250 accepted friendships." } },
  },
  {
    code: "FRIENDS_05_4",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "FRIENDSHIPS", min: 300 }],
    copy: { es: { title: "Conector social IV", description: "Alcanzá 300 amistades aceptadas." }, en: { title: "Social connector IV", description: "Reach 300 accepted friendships." } },
  },
  {
    code: "FRIENDS_05_5",
    category: "SOCIAL",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "FRIENDSHIPS", min: 350 }],
    copy: { es: { title: "Conector social V", description: "Alcanzá 350 amistades aceptadas." }, en: { title: "Social connector V", description: "Reach 350 accepted friendships." } },
  },
  {
    code: "FRIENDS_06_1",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "FRIENDSHIPS", min: 400 }],
    copy: { es: { title: "Toda una comunidad I", description: "Alcanzá 400 amistades aceptadas." }, en: { title: "A whole community I", description: "Reach 400 accepted friendships." } },
  },
  {
    code: "FRIENDS_06_2",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "FRIENDSHIPS", min: 500 }],
    copy: { es: { title: "Toda una comunidad II", description: "Alcanzá 500 amistades aceptadas." }, en: { title: "A whole community II", description: "Reach 500 accepted friendships." } },
  },
  {
    code: "FRIENDS_06_3",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "FRIENDSHIPS", min: 600 }],
    copy: { es: { title: "Toda una comunidad III", description: "Alcanzá 600 amistades aceptadas." }, en: { title: "A whole community III", description: "Reach 600 accepted friendships." } },
  },
  {
    code: "FRIENDS_06_4",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "FRIENDSHIPS", min: 750 }],
    copy: { es: { title: "Toda una comunidad IV", description: "Alcanzá 750 amistades aceptadas." }, en: { title: "A whole community IV", description: "Reach 750 accepted friendships." } },
  },
  {
    code: "FRIENDS_06_5",
    category: "SOCIAL",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "FRIENDSHIPS", min: 1000 }],
    copy: { es: { title: "Toda una comunidad V", description: "Alcanzá 1.000 amistades aceptadas." }, en: { title: "A whole community V", description: "Reach 1,000 accepted friendships." } },
  },
  {
    code: "LEVEL_01_1",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 2 }],
    copy: { es: { title: "Primer ascenso I", description: "Alcanzá el nivel 2." }, en: { title: "First ascent I", description: "Reach level 2." } },
  },
  {
    code: "LEVEL_01_2",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 3 }],
    copy: { es: { title: "Primer ascenso II", description: "Alcanzá el nivel 3." }, en: { title: "First ascent II", description: "Reach level 3." } },
  },
  {
    code: "LEVEL_01_3",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 4 }],
    copy: { es: { title: "Primer ascenso III", description: "Alcanzá el nivel 4." }, en: { title: "First ascent III", description: "Reach level 4." } },
  },
  {
    code: "LEVEL_01_4",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 6 }],
    copy: { es: { title: "Primer ascenso IV", description: "Alcanzá el nivel 6." }, en: { title: "First ascent IV", description: "Reach level 6." } },
  },
  {
    code: "LEVEL_01_5",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 7 }],
    copy: { es: { title: "Primer ascenso V", description: "Alcanzá el nivel 7." }, en: { title: "First ascent V", description: "Reach level 7." } },
  },
  {
    code: "LEVEL_02_1",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 8 }],
    copy: { es: { title: "Tomando impulso I", description: "Alcanzá el nivel 8." }, en: { title: "Building momentum I", description: "Reach level 8." } },
  },
  {
    code: "LEVEL_02_2",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 9 }],
    copy: { es: { title: "Tomando impulso II", description: "Alcanzá el nivel 9." }, en: { title: "Building momentum II", description: "Reach level 9." } },
  },
  {
    code: "LEVEL_02_3",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "LEVEL", min: 12 }],
    copy: { es: { title: "Tomando impulso III", description: "Alcanzá el nivel 12." }, en: { title: "Building momentum III", description: "Reach level 12." } },
  },
  {
    code: "LEVEL_02_4",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 15 }],
    copy: { es: { title: "Tomando impulso IV", description: "Alcanzá el nivel 15." }, en: { title: "Building momentum IV", description: "Reach level 15." } },
  },
  {
    code: "LEVEL_02_5",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 20 }],
    copy: { es: { title: "Tomando impulso V", description: "Alcanzá el nivel 20." }, en: { title: "Building momentum V", description: "Reach level 20." } },
  },
  {
    code: "LEVEL_03_1",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 25 }],
    copy: { es: { title: "Veterano I", description: "Alcanzá el nivel 25." }, en: { title: "Veteran I", description: "Reach level 25." } },
  },
  {
    code: "LEVEL_03_2",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 30 }],
    copy: { es: { title: "Veterano II", description: "Alcanzá el nivel 30." }, en: { title: "Veteran II", description: "Reach level 30." } },
  },
  {
    code: "LEVEL_03_3",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 35 }],
    copy: { es: { title: "Veterano III", description: "Alcanzá el nivel 35." }, en: { title: "Veteran III", description: "Reach level 35." } },
  },
  {
    code: "LEVEL_03_4",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 40 }],
    copy: { es: { title: "Veterano IV", description: "Alcanzá el nivel 40." }, en: { title: "Veteran IV", description: "Reach level 40." } },
  },
  {
    code: "LEVEL_03_5",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 45 }],
    copy: { es: { title: "Veterano V", description: "Alcanzá el nivel 45." }, en: { title: "Veteran V", description: "Reach level 45." } },
  },
  {
    code: "LEVEL_04_1",
    category: "PROGRESS",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "LEVEL", min: 50 }],
    copy: { es: { title: "Dominio I", description: "Alcanzá el nivel 50." }, en: { title: "Mastery I", description: "Reach level 50." } },
  },
  {
    code: "LEVEL_04_2",
    category: "PROGRESS",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 55 }],
    copy: { es: { title: "Dominio II", description: "Alcanzá el nivel 55." }, en: { title: "Mastery II", description: "Reach level 55." } },
  },
  {
    code: "LEVEL_04_3",
    category: "PROGRESS",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 60 }],
    copy: { es: { title: "Dominio III", description: "Alcanzá el nivel 60." }, en: { title: "Mastery III", description: "Reach level 60." } },
  },
  {
    code: "LEVEL_04_4",
    category: "PROGRESS",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 65 }],
    copy: { es: { title: "Dominio IV", description: "Alcanzá el nivel 65." }, en: { title: "Mastery IV", description: "Reach level 65." } },
  },
  {
    code: "LEVEL_04_5",
    category: "PROGRESS",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 70 }],
    copy: { es: { title: "Dominio V", description: "Alcanzá el nivel 70." }, en: { title: "Mastery V", description: "Reach level 70." } },
  },
  {
    code: "LEVEL_05_1",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 75 }],
    copy: { es: { title: "Élite I", description: "Alcanzá el nivel 75." }, en: { title: "Elite I", description: "Reach level 75." } },
  },
  {
    code: "LEVEL_05_2",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 80 }],
    copy: { es: { title: "Élite II", description: "Alcanzá el nivel 80." }, en: { title: "Elite II", description: "Reach level 80." } },
  },
  {
    code: "LEVEL_05_3",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 85 }],
    copy: { es: { title: "Élite III", description: "Alcanzá el nivel 85." }, en: { title: "Elite III", description: "Reach level 85." } },
  },
  {
    code: "LEVEL_05_4",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "LEVEL", min: 90 }],
    copy: { es: { title: "Élite IV", description: "Alcanzá el nivel 90." }, en: { title: "Elite IV", description: "Reach level 90." } },
  },
  {
    code: "LEVEL_05_5",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 95 }],
    copy: { es: { title: "Élite V", description: "Alcanzá el nivel 95." }, en: { title: "Elite V", description: "Reach level 95." } },
  },
  {
    code: "LEVEL_06_1",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 100 }],
    copy: { es: { title: "Más allá I", description: "Alcanzá el nivel 100." }, en: { title: "Beyond I", description: "Reach level 100." } },
  },
  {
    code: "LEVEL_06_2",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 110 }],
    copy: { es: { title: "Más allá II", description: "Alcanzá el nivel 110." }, en: { title: "Beyond II", description: "Reach level 110." } },
  },
  {
    code: "LEVEL_06_3",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 120 }],
    copy: { es: { title: "Más allá III", description: "Alcanzá el nivel 120." }, en: { title: "Beyond III", description: "Reach level 120." } },
  },
  {
    code: "LEVEL_06_4",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 130 }],
    copy: { es: { title: "Más allá IV", description: "Alcanzá el nivel 130." }, en: { title: "Beyond IV", description: "Reach level 130." } },
  },
  {
    code: "LEVEL_06_5",
    category: "PROGRESS",
    iconKey: "rocket",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 140 }],
    copy: { es: { title: "Más allá V", description: "Alcanzá el nivel 140." }, en: { title: "Beyond V", description: "Reach level 140." } },
  },
  {
    code: "LEVEL_07_1",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 150 }],
    copy: { es: { title: "Leyenda I", description: "Alcanzá el nivel 150." }, en: { title: "Legend I", description: "Reach level 150." } },
  },
  {
    code: "LEVEL_07_2",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "LEVEL", min: 160 }],
    copy: { es: { title: "Leyenda II", description: "Alcanzá el nivel 160." }, en: { title: "Legend II", description: "Reach level 160." } },
  },
  {
    code: "LEVEL_07_3",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 175 }],
    copy: { es: { title: "Leyenda III", description: "Alcanzá el nivel 175." }, en: { title: "Legend III", description: "Reach level 175." } },
  },
  {
    code: "LEVEL_07_4",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 190 }],
    copy: { es: { title: "Leyenda IV", description: "Alcanzá el nivel 190." }, en: { title: "Legend IV", description: "Reach level 190." } },
  },
  {
    code: "LEVEL_07_5",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 200 }],
    copy: { es: { title: "Leyenda V", description: "Alcanzá el nivel 200." }, en: { title: "Legend V", description: "Reach level 200." } },
  },
  {
    code: "LEVEL_08_1",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 225 }],
    copy: { es: { title: "Horizonte final I", description: "Alcanzá el nivel 225." }, en: { title: "Final horizon I", description: "Reach level 225." } },
  },
  {
    code: "LEVEL_08_2",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 250 }],
    copy: { es: { title: "Horizonte final II", description: "Alcanzá el nivel 250." }, en: { title: "Final horizon II", description: "Reach level 250." } },
  },
  {
    code: "LEVEL_08_3",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "LEVEL", min: 300 }],
    copy: { es: { title: "Horizonte final III", description: "Alcanzá el nivel 300." }, en: { title: "Final horizon III", description: "Reach level 300." } },
  },
  {
    code: "LEVEL_08_4",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "LEVEL", min: 400 }],
    copy: { es: { title: "Horizonte final IV", description: "Alcanzá el nivel 400." }, en: { title: "Final horizon IV", description: "Reach level 400." } },
  },
  {
    code: "LEVEL_08_5",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "LEVEL", min: 500 }],
    copy: { es: { title: "Horizonte final V", description: "Alcanzá el nivel 500." }, en: { title: "Final horizon V", description: "Reach level 500." } },
  },
  {
    code: "XP_01_1",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "XP", min: 250 }],
    copy: { es: { title: "Experiencia acumulada I", description: "Acumulá 250 XP en TFLives." }, en: { title: "Accumulated experience I", description: "Accumulate 250 XP in TFLives." } },
  },
  {
    code: "XP_01_2",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "XP", min: 500 }],
    copy: { es: { title: "Experiencia acumulada II", description: "Acumulá 500 XP en TFLives." }, en: { title: "Accumulated experience II", description: "Accumulate 500 XP in TFLives." } },
  },
  {
    code: "XP_01_3",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "XP", min: 1000 }],
    copy: { es: { title: "Experiencia acumulada III", description: "Acumulá 1.000 XP en TFLives." }, en: { title: "Accumulated experience III", description: "Accumulate 1,000 XP in TFLives." } },
  },
  {
    code: "XP_01_4",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 2,
    requirements: [{ metric: "XP", min: 2500 }],
    copy: { es: { title: "Experiencia acumulada IV", description: "Acumulá 2.500 XP en TFLives." }, en: { title: "Accumulated experience IV", description: "Accumulate 2,500 XP in TFLives." } },
  },
  {
    code: "XP_01_5",
    category: "PROGRESS",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "XP", min: 5000 }],
    copy: { es: { title: "Experiencia acumulada V", description: "Acumulá 5.000 XP en TFLives." }, en: { title: "Accumulated experience V", description: "Accumulate 5,000 XP in TFLives." } },
  },
  {
    code: "XP_02_1",
    category: "PROGRESS",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "XP", min: 10000 }],
    copy: { es: { title: "Camino recorrido I", description: "Acumulá 10.000 XP en TFLives." }, en: { title: "Road traveled I", description: "Accumulate 10,000 XP in TFLives." } },
  },
  {
    code: "XP_02_2",
    category: "PROGRESS",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "XP", min: 25000 }],
    copy: { es: { title: "Camino recorrido II", description: "Acumulá 25.000 XP en TFLives." }, en: { title: "Road traveled II", description: "Accumulate 25,000 XP in TFLives." } },
  },
  {
    code: "XP_02_3",
    category: "PROGRESS",
    iconKey: "star",
    xpReward: 0,
    coinReward: 4,
    requirements: [{ metric: "XP", min: 50000 }],
    copy: { es: { title: "Camino recorrido III", description: "Acumulá 50.000 XP en TFLives." }, en: { title: "Road traveled III", description: "Accumulate 50,000 XP in TFLives." } },
  },
  {
    code: "XP_02_4",
    category: "PROGRESS",
    iconKey: "star",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "XP", min: 100000 }],
    copy: { es: { title: "Camino recorrido IV", description: "Acumulá 100.000 XP en TFLives." }, en: { title: "Road traveled IV", description: "Accumulate 100,000 XP in TFLives." } },
  },
  {
    code: "XP_02_5",
    category: "PROGRESS",
    iconKey: "star",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "XP", min: 250000 }],
    copy: { es: { title: "Camino recorrido V", description: "Acumulá 250.000 XP en TFLives." }, en: { title: "Road traveled V", description: "Accumulate 250,000 XP in TFLives." } },
  },
  {
    code: "XP_03_1",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "XP", min: 500000 }],
    copy: { es: { title: "Reserva de experiencia I", description: "Acumulá 500.000 XP en TFLives." }, en: { title: "Experience reserve I", description: "Accumulate 500,000 XP in TFLives." } },
  },
  {
    code: "XP_03_2",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 7,
    requirements: [{ metric: "XP", min: 750000 }],
    copy: { es: { title: "Reserva de experiencia II", description: "Acumulá 750.000 XP en TFLives." }, en: { title: "Experience reserve II", description: "Accumulate 750,000 XP in TFLives." } },
  },
  {
    code: "XP_03_3",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "XP", min: 1000000 }],
    copy: { es: { title: "Reserva de experiencia III", description: "Acumulá 1.000.000 XP en TFLives." }, en: { title: "Experience reserve III", description: "Accumulate 1,000,000 XP in TFLives." } },
  },
  {
    code: "XP_03_4",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "XP", min: 1500000 }],
    copy: { es: { title: "Reserva de experiencia IV", description: "Acumulá 1.500.000 XP en TFLives." }, en: { title: "Experience reserve IV", description: "Accumulate 1,500,000 XP in TFLives." } },
  },
  {
    code: "XP_03_5",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "XP", min: 2000000 }],
    copy: { es: { title: "Reserva de experiencia V", description: "Acumulá 2.000.000 XP en TFLives." }, en: { title: "Experience reserve V", description: "Accumulate 2,000,000 XP in TFLives." } },
  },
  {
    code: "XP_04_1",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "XP", min: 3000000 }],
    copy: { es: { title: "Experiencia absoluta I", description: "Acumulá 3.000.000 XP en TFLives." }, en: { title: "Absolute experience I", description: "Accumulate 3,000,000 XP in TFLives." } },
  },
  {
    code: "XP_04_2",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "XP", min: 5000000 }],
    copy: { es: { title: "Experiencia absoluta II", description: "Acumulá 5.000.000 XP en TFLives." }, en: { title: "Absolute experience II", description: "Accumulate 5,000,000 XP in TFLives." } },
  },
  {
    code: "XP_04_3",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "XP", min: 10000000 }],
    copy: { es: { title: "Experiencia absoluta III", description: "Acumulá 10.000.000 XP en TFLives." }, en: { title: "Absolute experience III", description: "Accumulate 10,000,000 XP in TFLives." } },
  },
  {
    code: "XP_04_4",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "XP", min: 15000000 }],
    copy: { es: { title: "Experiencia absoluta IV", description: "Acumulá 15.000.000 XP en TFLives." }, en: { title: "Absolute experience IV", description: "Accumulate 15,000,000 XP in TFLives." } },
  },
  {
    code: "XP_04_5",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "XP", min: 25000000 }],
    copy: { es: { title: "Experiencia absoluta V", description: "Acumulá 25.000.000 XP en TFLives." }, en: { title: "Absolute experience V", description: "Accumulate 25,000,000 XP in TFLives." } },
  },
  {
    code: "IDENTITY_FOUNDATION",
    category: "IDENTITY",
    iconKey: "star",
    xpReward: 0,
    coinReward: 5,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "EMAIL_VERIFIED", min: 1 }],
    copy: { es: { title: "Base sólida", description: "Completá tu perfil y verificá tu correo." }, en: { title: "Solid foundation", description: "Complete your profile and verify your email." } },
  },
  {
    code: "IDENTITY_CONNECTED",
    category: "IDENTITY",
    iconKey: "zap",
    xpReward: 0,
    coinReward: 5,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "OAUTH_CONNECTIONS", min: 1 }],
    copy: { es: { title: "Identidad conectada", description: "Completá tu perfil y vinculá al menos una cuenta externa." }, en: { title: "Connected identity", description: "Complete your profile and link at least one external account." } },
  },
  {
    code: "IDENTITY_DUAL_LINK",
    category: "IDENTITY",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 8,
    requirements: [{ metric: "OAUTH_CONNECTIONS", min: 2 }],
    copy: { es: { title: "Doble vínculo", description: "Vinculá dos cuentas externas a TFLives." }, en: { title: "Double link", description: "Link two external accounts to TFLives." } },
  },
  {
    code: "IDENTITY_ESTABLISHED",
    category: "IDENTITY",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 10,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "EMAIL_VERIFIED", min: 1 }, { metric: "LEVEL", min: 10 }],
    copy: { es: { title: "Identidad establecida", description: "Completá tu identidad y alcanzá el nivel 10." }, en: { title: "Established identity", description: "Complete your identity and reach level 10." } },
  },
  {
    code: "IDENTITY_SOCIAL_ROOTS",
    category: "IDENTITY",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 10,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "FRIENDSHIPS", min: 10 }],
    copy: { es: { title: "Raíces en la comunidad", description: "Completá tu perfil y alcanzá 10 amistades." }, en: { title: "Community roots", description: "Complete your profile and reach 10 friendships." } },
  },
  {
    code: "IDENTITY_PUBLIC_VOICE",
    category: "IDENTITY",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 10,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "GLOBAL_MESSAGES", min: 100 }],
    copy: { es: { title: "Una voz reconocible", description: "Completá tu perfil y enviá 100 mensajes globales." }, en: { title: "A recognizable voice", description: "Complete your profile and send 100 global messages." } },
  },
  {
    code: "IDENTITY_PRIVATE_VOICE",
    category: "IDENTITY",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 10,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "DIRECT_MESSAGES", min: 100 }],
    copy: { es: { title: "Conversador identificado", description: "Completá tu perfil y enviá 100 mensajes privados." }, en: { title: "Known conversationalist", description: "Complete your profile and send 100 direct messages." } },
  },
  {
    code: "IDENTITY_FORTIFIED",
    category: "IDENTITY",
    iconKey: "swords",
    xpReward: 0,
    coinReward: 15,
    requirements: [{ metric: "EMAIL_VERIFIED", min: 1 }, { metric: "OAUTH_CONNECTIONS", min: 1 }, { metric: "LEVEL", min: 20 }],
    copy: { es: { title: "Cuenta fortificada", description: "Verificá tu correo, conectá una cuenta externa y alcanzá el nivel 20." }, en: { title: "Fortified account", description: "Verify your email, connect an external account, and reach level 20." } },
  },
  {
    code: "IDENTITY_RECOGNIZED",
    category: "IDENTITY",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "FRIENDSHIPS", min: 25 }, { metric: "LEVEL", min: 25 }],
    copy: { es: { title: "Nombre conocido", description: "Completá tu perfil, alcanzá 25 amistades y el nivel 25." }, en: { title: "Known name", description: "Complete your profile, reach 25 friendships, and level 25." } },
  },
  {
    code: "IDENTITY_COMPLETE_JOURNEY",
    category: "IDENTITY",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "PROFILE_COMPLETE", min: 1 }, { metric: "EMAIL_VERIFIED", min: 1 }, { metric: "OAUTH_CONNECTIONS", min: 2 }, { metric: "LEVEL", min: 50 }],
    copy: { es: { title: "Identidad definitiva", description: "Completá tu identidad, vinculá dos cuentas y alcanzá el nivel 50." }, en: { title: "Definitive identity", description: "Complete your identity, link two accounts, and reach level 50." } },
  },
  {
    code: "JOURNEY_BALANCED_START",
    category: "PROGRESS",
    iconKey: "star",
    xpReward: 0,
    coinReward: 8,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 25 }, { metric: "DIRECT_MESSAGES", min: 25 }, { metric: "FRIENDSHIPS", min: 2 }, { metric: "LEVEL", min: 5 }],
    copy: { es: { title: "Primer equilibrio", description: "Participá en chat, mensajes privados, amistades y progreso temprano." }, en: { title: "Balanced start", description: "Take part in chat, direct messages, friendships, and early progression." } },
  },
  {
    code: "JOURNEY_COMMUNITY_REGULAR",
    category: "PROGRESS",
    iconKey: "flame",
    xpReward: 0,
    coinReward: 10,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 100 }, { metric: "DIRECT_MESSAGES", min: 100 }, { metric: "FRIENDSHIPS", min: 5 }, { metric: "LEVEL", min: 10 }],
    copy: { es: { title: "Miembro habitual", description: "Alcanzá 100 mensajes globales, 100 privados, 5 amistades y nivel 10." }, en: { title: "Community regular", description: "Reach 100 global messages, 100 direct messages, 5 friendships, and level 10." } },
  },
  {
    code: "JOURNEY_SOCIAL_PULSE",
    category: "PROGRESS",
    iconKey: "heart",
    xpReward: 0,
    coinReward: 12,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 500 }, { metric: "DIRECT_MESSAGES", min: 500 }, { metric: "FRIENDSHIPS", min: 10 }, { metric: "LEVEL", min: 20 }],
    copy: { es: { title: "Pulso social", description: "Construí una presencia equilibrada en toda la comunidad." }, en: { title: "Social pulse", description: "Build a balanced presence across the community." } },
  },
  {
    code: "JOURNEY_ESTABLISHED",
    category: "PROGRESS",
    iconKey: "medal",
    xpReward: 0,
    coinReward: 15,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 1000 }, { metric: "DIRECT_MESSAGES", min: 1000 }, { metric: "FRIENDSHIPS", min: 20 }, { metric: "LEVEL", min: 30 }],
    copy: { es: { title: "Miembro establecido", description: "Llegá a 1.000 mensajes globales, 1.000 privados, 20 amistades y nivel 30." }, en: { title: "Established member", description: "Reach 1,000 global messages, 1,000 direct messages, 20 friendships, and level 30." } },
  },
  {
    code: "JOURNEY_CORE_MEMBER",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 18,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 5000 }, { metric: "DIRECT_MESSAGES", min: 5000 }, { metric: "FRIENDSHIPS", min: 35 }, { metric: "LEVEL", min: 50 }],
    copy: { es: { title: "Parte del núcleo", description: "Convertite en una presencia constante en cada parte social de TFLives." }, en: { title: "Core member", description: "Become a steady presence across every social side of TFLives." } },
  },
  {
    code: "JOURNEY_VETERAN",
    category: "PROGRESS",
    iconKey: "trophy",
    xpReward: 0,
    coinReward: 20,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 10000 }, { metric: "DIRECT_MESSAGES", min: 10000 }, { metric: "FRIENDSHIPS", min: 50 }, { metric: "LEVEL", min: 75 }],
    copy: { es: { title: "Veterano integral", description: "Alcanzá una trayectoria veterana en chat, DMs, amistades y nivel." }, en: { title: "All-round veteran", description: "Reach veteran status in chat, DMs, friendships, and level." } },
  },
  {
    code: "JOURNEY_PILLAR",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 25,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 25000 }, { metric: "DIRECT_MESSAGES", min: 25000 }, { metric: "FRIENDSHIPS", min: 75 }, { metric: "LEVEL", min: 100 }],
    copy: { es: { title: "Pilar de TFLives", description: "Alcanzá 25.000 mensajes globales y privados, 75 amistades y nivel 100." }, en: { title: "TFLives pillar", description: "Reach 25,000 global and direct messages, 75 friendships, and level 100." } },
  },
  {
    code: "JOURNEY_ICON",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 30,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 100000 }, { metric: "DIRECT_MESSAGES", min: 100000 }, { metric: "FRIENDSHIPS", min: 150 }, { metric: "LEVEL", min: 150 }],
    copy: { es: { title: "Ícono de la comunidad", description: "Dejá una huella enorme en todas las áreas sociales de TFLives." }, en: { title: "Community icon", description: "Leave a huge mark across every social area of TFLives." } },
  },
  {
    code: "JOURNEY_MYTHIC",
    category: "PROGRESS",
    iconKey: "gem",
    xpReward: 0,
    coinReward: 40,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 250000 }, { metric: "DIRECT_MESSAGES", min: 250000 }, { metric: "FRIENDSHIPS", min: 300 }, { metric: "LEVEL", min: 250 }],
    copy: { es: { title: "Trayectoria mítica", description: "Alcanzá hitos extraordinarios de actividad, conexiones y progreso." }, en: { title: "Mythic journey", description: "Reach extraordinary milestones in activity, connections, and progression." } },
  },
  {
    code: "JOURNEY_TFL_LEGEND",
    category: "PROGRESS",
    iconKey: "crown",
    xpReward: 0,
    coinReward: 50,
    requirements: [{ metric: "GLOBAL_MESSAGES", min: 500000 }, { metric: "DIRECT_MESSAGES", min: 500000 }, { metric: "FRIENDSHIPS", min: 500 }, { metric: "LEVEL", min: 500 }],
    copy: { es: { title: "Leyenda de TFLives", description: "Completá una trayectoria reservada para las mayores leyendas de TFLives." }, en: { title: "TFLives legend", description: "Complete a journey reserved for the greatest TFLives legends." } },
  }
] as const satisfies readonly ProgressionAchievement[];

export const PROGRESSION_ACHIEVEMENTS: readonly ProgressionAchievement[] = [
  ...LEGACY_PROGRESSION_ACHIEVEMENTS,
  ...PRODUCTION_PROGRESSION_ACHIEVEMENTS,
];

export type ProgressionAchievementCode = string;

export const PROGRESSION_ACHIEVEMENTS_BY_CODE = new Map<string, ProgressionAchievement>(
  PROGRESSION_ACHIEVEMENTS.map((achievement) => [achievement.code, achievement]),
);

export const PRODUCTION_ACHIEVEMENT_COUNT = PRODUCTION_PROGRESSION_ACHIEVEMENTS.length;

export function progressionAchievementCopy(achievement: ProgressionAchievement, locale: string) {
  return locale === "en" ? achievement.copy.en : achievement.copy.es;
}
